site_blogueuses_ecole:
    path:     /ecole/{ecole_slug}/blogueuses
    defaults: { _controller: ViwebBlogueuseBundle:Blogueuse:ecole }
    
site_blogueuse_profil:
    path:     /ecole/{ecole_slug}/blogueuse/{blogueuse_id}
    defaults: { _controller: ViwebBlogueuseBundle:Blogueuse:profil }
    
site_blogueuse_article:
    path:     /ecole/{ecole_slug}/blogueuse/{blogueuse_id}/{article_slug}
    defaults: { _controller: ViwebBlogueuseBundle:Blogueuse:article }