<?php

namespace Viweb\RealisationBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealisationRepository extends \Doctrine\ORM\EntityRepository
{

}
