# nixpacks.toml

[variables]
APP_ENV = "prod"
APP_DEBUG = "0"
COMPOSER_MEMORY_LIMIT = "-1"
COMPOSER_ALLOW_SUPERUSER = "1"

# Facultatif : si tu veux aider la résolution Composer sans casser le runtime.
# Voir aussi la section "PHP" plus bas concernant la version.
# (À mettre dans composer.json > config.platform.php = "7.4.33")

[phases.setup]
# ajoute ici des paquets dont ton app a besoin (ex: unzip, git, …)
# Nixpacks fournit déjà PHP/Composer automatiquement pour les projets PHP. :contentReference[oaicite:1]{index=1}
packages = ["git", "unzip"]

[phases.install]
# IMPORTANT: on n’exécute AUCUN script Composer en build
cmds = [
  "composer diagnose || true",
  "composer install -n --no-dev --prefer-dist --optimize-autoloader --no-plugins --no-scripts --ignore-platform-req=php -vvv"

]

# (optionnel) si tu as un build front (encorejs/webpack), ajoute une phase build ici

# On ne définit PAS de phase start ici ; on mettra la commande de démarrage dans Kinsta (Processes)
