# --- System packages from Nix ---
[phases.setup]
# Use PHP 7.4 to satisfy your locked deps
nixPkgs = [
  "php74",
  "php74Extensions.mbstring",
  "php74Extensions.intl",
  "php74Extensions.pdo_mysql",
  "php74Extensions.zip",
  "nodejs_20",
  "yarn",
  "git"
]

# --- Install: Composer outside Nix so no Yarn/Composer collision ---
[phases.install]
cmds = [
  "set -euxo pipefail",
  # install composer in a PATH dir
  "php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\"",
  "php composer-setup.php --install-dir=/bin --filename=composer",
  "rm -f composer-setup.php",
  "composer --version",
  # install PHP deps
  "COMPOSER_ALLOW_SUPERUSER=1 composer install --no-interaction --prefer-dist --no-progress"
]

# --- Build (only if you actually have a JS step) ---
[phases.build]
cmds = [
  "yarn install --frozen-lockfile || true",
  "yarn build || true",
  # warm Symfony cache for prod
  "php bin/console cache:clear --env=prod || true"
]

[variables]
COMPOSER_ALLOW_SUPERUSER = "1"

[start]
# Adjust if your entrypoint differs
cmd = "php -S 0.0.0.0:${PORT} -t web web/app.php"
