viweb_seo_homepage:
    path:     /seo
    defaults: { _controller: ViwebSeoBundle:Seo:index }

viweb_seo_homepage:
    path:     /seo
    defaults: { _controller: ViwebSeoBundle:Seo:index }
    
viweb_seo_add:
    path:     /seo/add
    defaults: { _controller: ViwebSeoBundle:Seo:add }

viweb_motcle_add:
    path:     /motscles/add
    defaults: { _controller: ViwebSeoBundle:Motscles:add }
    