<?php

namespace Viweb\EcoleBundle\Repository;

/**
 * EcoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcoleRepository extends \Doctrine\ORM\EntityRepository
{
    function findbySlug($slug)
    {

        $qb = $this->createQueryBuilder('e')

            ->where('e.slug  = :slug')
            ->setParameter('slug', $slug);


        return $qb
            ->getQuery()
            ->getResult();
    }
    
    
    
  
    
    function findIdBySlug($ecole_slug)
    {

        $qb = $this->createQueryBuilder('e')
            
            
            ->where('e.slug = :slug' )
            ->setParameter('slug', $ecole_slug);
            
            
        

        return $qb
            ->getQuery()
            ->getResult();
    }
    
    
    
    
    

}
