<?php

namespace Viweb\EcoleBundle\Repository;

/**
 * MessageEcoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageEcoleRepository extends \Doctrine\ORM\EntityRepository
{
}
