<?php

namespace Viweb\BlogueuseBundle\Repository;

/**
 * BlogueuseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogueuseRepository extends \Doctrine\ORM\EntityRepository
{
    
    
    
    
    
    function findBlogueuseByEcoleId($ecole_id)
    {

        $qb = $this->createQueryBuilder('b');

            // On fait une jointure avec l'entité Category avec pour alias « c »
            $qb
              ->innerJoin('b.ecole', 'e')
              ->addSelect('e')
            ;

            // Puis on filtre sur le nom des catégories à l'aide d'un IN
            $qb->where($qb->expr()->in('e.id', $ecole_id));
            // La syntaxe du IN et d'autres expressions se trouve dans la documentation Doctrine

            // Enfin, on retourne le résultat
            return $qb
              ->getQuery()
              ->getResult()
            ;
    }
    
    
    
    function findByEcole($id, $archive = '')
    {


        $start_date = new \DateTime();
        $start_date->setTimestamp(mktime());
        $qb = $this->createQueryBuilder('b');

        $qb
            ->where('b.ecole  = :ecole')                      
            ->andwhere("b.datePlanification <= :dateplan")
            ->setParameter('ecole', $id)
            ->setParameter('dateplan', $start_date)
            ->orderBy('b.nom', 'ASC');
        if(!empty($archive))  {
            $qb
              ->andWhere('b.datePlanification >= :archive')
              ->setParameter('archive', new \DateTime('2018-09-01') );
        }    

        return $qb
            ->getQuery()
            ->getResult();
    }
}
