<?php

namespace Viweb\CarouselBundle\Repository;

/**
 * CarouselRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarouselRepository extends \Doctrine\ORM\EntityRepository
{
}
