<?php

namespace Viweb\SoumissionBundle\Repository;

/**
 * SoumissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoumissionRepository extends \Doctrine\ORM\EntityRepository
{
}
