<?php

namespace Viweb\TemoignageBundle\Repository;

/**
 * TemoignageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemoignageRepository extends \Doctrine\ORM\EntityRepository
{
    
    
    
    
}


