<?php

namespace Viweb\SeoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MotsclesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotsclesRepository extends \Doctrine\ORM\EntityRepository
{
      public function getLikeQueryBuilder($pattern)
          {
            return $this
              ->createQueryBuilder('m')
              ->where('m.motcle LIKE :pattern')
              ->setParameter('pattern', $pattern)
            ;
          }
}
