<?php

namespace Viweb\SeoBundle\Repository;

/**
 * OpenGraphRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpenGraphRepository extends \Doctrine\ORM\EntityRepository
{
}
