<?php

namespace Viweb\MailchimpBundle\Repository;

/**
 * MailchimpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailchimpRepository extends \Doctrine\ORM\EntityRepository
{
}
